### PR TITLE
Add initial support for series naming and folder structure

### PR DESCRIPTION
**Pull request by odinuge**
Add initial support for series naming and folder structure. The majority of the work is done by @eithe.

All testing and proposals for improvements are welcome!

### CODE REVIEW

**Comment by odinuge** [comment]
This fixes #26 and #23.

**Comment by ralin3** [comment]
This works good, but it is inconsistent - files are created with a period instead of space.
Folders are created with spaces.

It should be either one, and in my opinion it should not be with spaces anywhere.

**Comment by odinuge** [comment]
Hi @ralin3,

Agree about the consistency, and spaced should be omitted. 

This still needs some testing and a few finishing touches. Will defensively look at your example :+1:

**Comment by ralin3** [comment]
Been using this with the filenaming-option for about a month now, no issues with "regular" shows.
Only issues are with shows that use date as episodename, ie. barnas supershow.

If that can be fixed, this is more than good enough for merging.
For suggestions for naming:
https://support.plex.tv/hc/en-us/articles/200381053-Naming-Date-based-TV-Shows

**Comment by odinuge** [comment]
Looks like this works well now! :+1: 

Feel free to send another PR with improvements

**Pull request merged**
